### ISSUE TITLE
questions about MSCOCO data

### ISSUE THREAD

**Issue by xixiareone** [m2man/LGSGM#1]
thanks for your great work for A Deep Local and Global Scene Graph Matching for Image-Text Retrieval . I am interested in your work. Could you share scene graph data about MSCOCO？
Many thanks!

**Comment by m2man** [comment]
You can find the original scene graph data of images and text (and also its preprocessed) [here](https://drive.google.com/drive/folders/1Q1Msy6kV0pzZ7uxrDjDQW34Ta9CucI4i?usp=sharing). The original data is given by the authors of the SGM [paper](https://arxiv.org/abs/1910.05134).
