### ISSUE TITLE
Graph data on Flickr30K

### ISSUE THREAD

**Issue by gedaye11** [m2man/LGSGM#2]
thanks for your great work! Could you share scene graph data on Flickr30K？
Thanks!

**Comment by m2man** [comment]
Hi,
Thank you for your interest. You can find the scene graph data on Flickr30K in the **Data Folder**. They are named as **flickr30k_val/train/test_lowered_images_data.joblib**.
By the way, I also uploaded the data for MSCOCO and you can find it on Readme page.

**Comment by gedaye11** [comment]
Thanks~

**Comment by gedaye11** [comment]
Hi, I think the files of "flickr30k_train_lowered_images/cap_data.joblib" are missing. could you add them?

**Comment by m2man** [comment]
Due to the size limit of file uploading to Github, I uploaded it on Google Drive instead. You can find it [here](https://drive.google.com/drive/folders/1ZbyeezvaxA20fM7lmxDNL0UnyHX8wLjt?usp=sharing).
