### ISSUE TITLE
scene graph generation

### ISSUE THREAD

**Issue by DeepaliVerma** [m2man/LGSGM#3]
Sir, can you please provide me code for generating scene graph from a sentence and image.

**Comment by m2man** [comment]
Hi, thank you for your interest in our research. I am sorry that I don't have the code for generating scene graphs as we used the generated data from the SGM research's authors. You can find more information about the code by contacting them directly [here](https://arxiv.org/pdf/1910.05134.pdf). 
Basically, they used MSDN and Neural Motif to generate graphs for visual images (for MSCOCO and Flickr30k respectively). They used SPICE to generate graphs from textual captions.

**Comment by dddszt** [comment]
Hi, thank you for your work. Could you please share the file of "flickr30k_test_caps_with_rel.json" ?
Thank you!
