### ISSUE TITLE
flickr30k_test_caps_with_rel.json

### ISSUE THREAD

**Issue by dddszt** [m2man/LGSGM#4]
Hi, thank you for your work. Could you please share the file of "flickr30k_test_caps_with_rel.json" ?
Thank you!

**Comment by m2man** [comment]
Hi, you can find these files [here](https://drive.google.com/drive/folders/1ZbyeezvaxA20fM7lmxDNL0UnyHX8wLjt). Indeed, these files were only used to match the captions with their ids in the dataset.

**Comment by dddszt** [comment]
Thank you.
