### ISSUE TITLE
About SGM source code and data

### ISSUE THREAD

**Issue by MartinYuanNJU** [m2man/LGSGM#5]
Hi there! I just want to ask about the source code and data of the work SGM. In your repository you said your data (Flickr30k) is original given by the SGM paper, and I wonder how do you obtain the SGM's source code and preprocessed data, cause I cannot find any repository for SGM on Github.  Do you send e-mail to the authors of SGM and they send back about their data and code, which hasn't been opened on Github? Thanks a lot for your answer!

**Comment by m2man** [comment]
Hi, regarding the code, the authors mentioned it in their official paper version for WACV 2020. You can find it in the footnote on page 6 ([here](https://openaccess.thecvf.com/content_WACV_2020/papers/Wang_Cross-modal_Scene_Graph_Matching_for_Relationship-aware_Image-Text_Retrieval_WACV_2020_paper.pdf)). However, it seems like the link does not work anymore.
And yes, I contacted them through email to get their data and pretrained model. So you maybe want to send them an email to get the code and other stuff for your interests.

**Comment by MartinYuanNJU** [comment]
Thanks a lot! The link to the project code they presents in the paper is unable to access, maybe I'll try a few more times later.   I also want to ask whether you got the source code of SGM after you contacted with the authors, or they only provided you with preprocessed data and pre-trained model?

**Comment by m2man** [comment]
Nah I got the source code from the link they wrote in the paper. The preprocessed data and pre-trained model were after I contacted them through email. I also discussed with them several things I did not understand in their model by email. But since the link is broken, if you want to get the code I think you need to contact them.

**Comment by MartinYuanNJU** [comment]
Thanks! I have already sent e-mail to them asking for the source code. Thanks again for your patience to answer my questions!

**Comment by m2man** [comment]
You're welcome. If you have any questions about the project, please don't hesitate to contact me through github or my email.

**Comment by TreezzZ** [comment]
Hi! I have the same problem. 
Have u got the code about scene graph generation?

**Comment by MartinYuanNJU** [comment]
> Hi! I have the same problem.
> Have u got the code about scene graph generation?

Hello! Yes I've got the source code and processed dataset of SGM. The server of SGM's authors' lab is under maintenance, so they posts a Baidu Netdisk link which contains the source code and dataset they used for SGM, could you please send me your e-mail address where I can send the Baidu Netdisk link to you?

**Comment by TreezzZ** [comment]
> > Hi! I have the same problem.
> > Have u got the code about scene graph generation?
> 
> Hello! Yes I've got the source code and processed dataset of SGM. The server of SGM's authors' lab is under maintenance, so they posts a Baidu Netdisk link which contains the source code and dataset they used for SGM, could you please send me your e-mail address where I can send the Baidu Netdisk link to you?

Great! My email address is smz5505@psu.edu
Thanks!

**Comment by MartinYuanNJU** [comment]
> > > Hi! I have the same problem.
> > > Have u got the code about scene graph generation?
> > 
> > 
> > Hello! Yes I've got the source code and processed dataset of SGM. The server of SGM's authors' lab is under maintenance, so they posts a Baidu Netdisk link which contains the source code and dataset they used for SGM, could you please send me your e-mail address where I can send the Baidu Netdisk link to you?
> 
> Great! My email address is [smz5505@psu.edu](mailto:smz5505@psu.edu) Thanks!

I've just sent the e-mail to you, please check and accept :)

**Comment by TreezzZ** [comment]
Thank you! But I still not receive the e-mail, could you check it? My e-mail address is SMZ5505@psu.edu. Or you can send the email to shuzhao.cs@gmail.com
Thanks again!

**Comment by MartinYuanNJU** [comment]
> Thank you! But I still not receive the e-mail, could you check it? My e-mail address is [SMZ5505@psu.edu](mailto:SMZ5505@psu.edu). Or you can send the email to [shuzhao.cs@gmail.com](mailto:shuzhao.cs@gmail.com)
> Thanks again!

Maybe is because the upper and lower case letters, in your first reply your e-mail address is smz5505@psu.edu. 
I've sent the e-mail to the upper letters' email address SMZ5505@psu.edu, hope you can successfully receive it :)

**Comment by hhhhhhx** [comment]
@MartinYuanNJU  Could you please send me the Baidu Netdisk link too?
My e-mail address is huangxu@whu.edu.cn
Thanks!

**Comment by MartinYuanNJU** [comment]
> @MartinYuanNJU Could you please send me the Baidu Netdisk link too?
> My e-mail address is [huangxu@whu.edu.cn](mailto:huangxu@whu.edu.cn)
> Thanks!

I've just sent the e-mail to you, please check and accept :)

**Comment by hhhuangxu** [comment]
> > @MartinYuanNJU Could you please send me the Baidu Netdisk link too?
> > My e-mail address is [huangxu@whu.edu.cn](mailto:huangxu@whu.edu.cn)
> > Thanks!
> 
> I've just sent the e-mail to you, please check and accept :)

Received, thanks again!

**Comment by Qi-Chuan** [comment]
@MartinYuanNJU Could you please send me the Baidu Netdisk link too?
My e-mail address is 920892753@qq.com
Thanks!

**Comment by MartinYuanNJU** [comment]
> @MartinYuanNJU Could you please send me the Baidu Netdisk link too?
> My e-mail address is [920892753@qq.com](mailto:920892753@qq.com)
> Thanks!

Of course, I've just sent the link to your e-mail address, hope you can receive it successfully :).

**Comment by Qi-Chuan** [comment]
> 

Thanks again！ I've received!

**Comment by Qi-Chuan** [comment]
> > @MartinYuanNJU Could you please send me the Baidu Netdisk link too?
> > My e-mail address is [920892753@qq.com](mailto:920892753@qq.com)
> > Thanks!
> 
> Of course, I've just sent the link to your e-mail address, hope you can receive it successfully :).

I've received, thanks!

**Comment by freya-7** [comment]
Hello, this is a very good piece of work, thanks for your contributions! Can you send me the SGM source code/dataset/pre-trained model, I need them very much. My email is： yuyunqian2022@163.com
