### ISSUE TITLE
About SGM work's source code

### ISSUE THREAD

**Issue by MartinYuanNJU** [m2man/LGSGM#6]
Hi! Last week I tried to contact to the author of SGM to acquire source code of SGM (cause I want to know how they use Neural Motifs to generate scene graph for each image in Flickr30k and MS-COCO and how they transform object regions and relationship between regions detected by Neural Motifs into vectors by Faster-RCNN pertained on Visual Genome), one week passed and they haven't replied me yet. Do you send e-mail to this address: sijin.wang@vipl.ict.ac.cn ? Thanks for your answer.

**Comment by m2man** [comment]
That time (July 2020), I sent the email to Dr. Wang Ruiping and his email is: wangruiping@ict.ac.cn
However, I am not sure if he still uses this email or not. But you can try.
By the way, sometimes he is really busy and I used to wait a week for his response.

**Comment by MartinYuanNJU** [comment]
All right. I'll try it.
