### ISSUE TITLE
Could you please tell me where to find the SGM original code?

### ISSUE THREAD

**Issue by hhhuangxu** [m2man/LGSGM#7]
Could you please tell me where to find the SGM original code? Thank you.
(the original code of "Cross-modal Scene Graph Matching for Relationship-aware Image-Text Retrieval")

**Comment by m2man** [comment]
Hi, you can see issue #5. Hope that you can find the answer there.
Their source code was mentioned in their paper, but the link is currently broken. So I think you should send an email to the authors to get the code and pretrained models.
